from __future__ import annotations

YAHOO_ITEM_SEARCH_URL = "https://shopping.yahooapis.jp/ShoppingWebService/V3/itemSearch"
YAHOO_ATTRIBUTION_TEXT = "Web Services by Yahoo! JAPAN"
YAHOO_ATTRIBUTION_URL = "https://developer.yahoo.co.jp/sitemap/"
YAHOO_PRODUCT_HOSTS = frozenset(
    {
        "shopping.yahoo.co.jp",
        "store.shopping.yahoo.co.jp",
        "paypaymall.yahoo.co.jp",
    }
)
YAHOO_IMAGE_HOSTS = frozenset({"item-shopping.c.yimg.jp"})

# Conservative, user-visible safety guard. Yahoo's category taxonomy is remote, so
# response filtering below complements this query denylist instead of replacing it.
RESTRICTED_SEARCH_TERMS = (
    "adult",
    "antibiotic",
    "bdsm",
    "bong",
    "bomb",
    "brass knuckles",
    "cannabis",
    "casino",
    "cbd",
    "cocaine",
    "counterfeit",
    "cracked software",
    "crossbow",
    "dab rig",
    "drug paraphernalia",
    "drug scale",
    "e-liquid",
    "explosive",
    "fentanyl",
    "firearm",
    "fireworks",
    "fake id",
    "fake pos",
    "fetish",
    "forged document",
    "gambling",
    "fertility hormone",
    "hgh",
    "heroin",
    "hidden tracker",
    "imsi catcher",
    "insulin",
    "keylogger",
    "live cam",
    "marijuana",
    "meth",
    "nicotine",
    "nicotine pouch",
    "opioid",
    "ozempic",
    "porn",
    "psilocybin",
    "ransomware",
    "replica",
    "sex toy",
    "sex doll",
    "skimmer",
    "spy camera",
    "spyware",
    "stun gun",
    "stolen goods",
    "switchblade",
    "taser",
    "thc",
    "tobacco",
    "testosterone",
    "vape",
    "weapon",
    "wildlife contraband",
    "アダルト",
    "インスリン",
    "オキシコドン",
    "オピオイド",
    "カジノ",
    "ギャンブル",
    "キーロガー",
    "クラックソフト",
    "クロスボウ",
    "コピー商品",
    "コカイン",
    "スタンガン",
    "ストーカーウェア",
    "スパイウェア",
    "タバコ",
    "たばこ",
    "テーザー",
    "ニコチン",
    "ボウガン",
    "ポルノ",
    "マルウェア",
    "マリファナ",
    "ランサムウェア",
    "リキッド",
    "偽造",
    "偽造品",
    "処方薬",
    "処方箋医薬品",
    "大麻",
    "大麻栽培",
    "媚薬",
    "弾薬",
    "性玩具",
    "性的サービス",
    "拳銃",
    "盗品",
    "盗聴",
    "監視カメラ",
    "空気銃",
    "経口避妊薬",
    "抗生物質",
    "花火",
    "薬物",
    "違法薬物",
    "銃",
    "銃器",
    "隠しカメラ",
    "麻薬",
    "覚醒剤",
    "爆弾",
    "爆発物",
    "催涙スプレー",
    "海賊版",
    "飛び出しナイフ",
    "電子タバコ",
    "追跡タグ",
    "ナックルダスター",
    "ボング",
    "ダブリグ",
)

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
DEFAULT_CACHE_TTL_SECONDS = 300
DEFAULT_BASE_RATE_SECONDS = 1.0
DEFAULT_WARNING_THRESHOLD = 45_000
DEFAULT_HARD_LIMIT = 50_000
DEFAULT_GLOBAL_RATE_LIMIT = 60
DEFAULT_GLOBAL_WINDOW_SECONDS = 60

STATE_DIRNAME = "state"
CACHE_DIRNAME = "cache"
