from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PreferenceGraphRepository(Protocol):
    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    async def get_profile_summary(self, subject_id: str) -> dict[str, Any]: ...

    async def route_spaces(self, subject_id: str, query: str, limit: int) -> dict[str, Any]: ...

    async def search_candidates(self, subject_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    async def get_neighborhood(self, subject_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    async def get_graph(self, subject_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    async def preview_mutation(self, subject_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    async def apply_mutation(
        self,
        subject_id: str,
        mutation_id: str,
        preview_hash: str,
    ) -> dict[str, Any]: ...

    async def export_graph(self, subject_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    async def delete_graph(self, subject_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    async def cleanup_expired(self) -> dict[str, int]: ...


@runtime_checkable
class MemorySearchBackend(Protocol):
    async def search_spaces(self, subject_id: str, query: str, limit: int) -> list[dict[str, Any]]: ...

    async def search_claims(self, subject_id: str, request: dict[str, Any]) -> list[dict[str, Any]]: ...
